---
title: "Descriptive _draft01_"
author: "CS-Team"
date: "2020 05 14"
output:
  html_document:
      toc: true
      toc_depth: 5
---

****

```{r setup, include=FALSE}

## 0.1: cleaing memory
rm(list=ls(all=T))

## 0.2 defining options
options(repos="https://cran.rstudio.com")
options(stringsAsFactors = FALSE)
knitr::opts_chunk$set(echo = TRUE, fig.width = 7, fig.height = 5)

## 0.3 installing and loading needed packages
# install & load packages
# install.packages("dplyr")
library(dplyr)
# install.packages("knitr")
library(knitr)
# install.packages("kableExtra")
library(kableExtra)
# install.packages("rvest")
library(rvest)
# install.packages("magrittr")
library(magrittr)
# install.packages("pageviews")
# library(pageviews)
# install.packages("WikipediR")
# library(WikipediR)
# install.packages("ggplot2")
# library(ggplot2)
# install.packages("tibble")
# library(tibble)
# install.packages("quanteda")
library(quanteda)
# install.packages("stargazer")
library(stargazer)
# install.packages("tidyr")
library(tidyr)
# install.packages("stringr")
library(stringr)
# install.packages("effects")
library(effects)


```

&nbsp;

***


### Change Log


* *draft01*
  + Erster Entwurf, Übertragen des `.doc-files` in Markdown
  
&nbsp;

***

### 0. Daten Einlesen & Vorbereiten


```{r 00, include = TRUE, results = TRUE, eval = TRUE, message = FALSE, warning = FALSE}

# Grunddatensatz Einlesen
data00 <- readRDS("./Rohdaten/df_all_data_draft07.rds")

# nur amtierende filtern
data00 <- data00 %>% filter(rat %in% c("SR", "NR"))

# Nachtrag Thomas Hurter
data00[which(data00$wiki_id == 97), c("district", "party_short", "region")] <- c("Schaffhausen", "SVP", "deu")
# Nachtrag Hannes Germann
data00[which(data00$wiki_id == 225), c("district", "party_short", "region")] <- c("Schaffhausen", "SVP", "deu")

# Kleinparteien den Fraktionen zuordnen
data00$party_short[data00$party_short=="ALG"] <- "GPS"
data00$party_short[data00$party_short=="BastA!"] <- "GPS"
data00$party_short[data00$party_short=="PdA"] <- "GPS"
data00$party_short[data00$party_short=="solid."] <- "GPS"
data00$party_short[data00$party_short=="LDP"] <- "FDP"
data00$party_short[data00$party_short=="EVP"] <- "CVP"
data00$party_short[data00$party_short=="BDP"] <- "CVP"
data00$party_short[data00$party_short=="EDU"] <- "SVP"
data00$party_short[data00$party_short=="Lega"] <- "SVP"
data00$party_short[data00$party_short=="Parteilos"] <- "SVP"

# status als faktor setzten
data00[ , "status"] <- as.factor(as.character(data00[ , "status"]))

#  Maenner und CVP als Referenzkategorien setzen
data00[ , "party_short"] <- as.factor(as.character(data00[, "party_short"]))
data00[ , "gender"] <- as.factor(as.character(data00[, "gender"]))
data00$gender <- relevel(x = data00$gender, ref = "m")
data00$party_short <- relevel(x = data00$party_short, ref = "CVP")



```



```{r 01, include = TRUE, results = FALSE, eval = TRUE, message = FALSE, warning = FALSE}



## Deskriptive Statistik Lebensbereiche
var_sel <- c("ausb_rel_prc_wiki" , "beruf_rel_prc_wiki",
             "enga_rel_prc_wiki", "poli_rel_prc_wiki", "priv_rel_prc_wiki")
# Speichern der Tabelle  
data00 %>% 
  select(., var_sel) %>% 
  stargazer(., type = "html", digits = 1, out = "./GrafikenTabellen/descr_lebr_draft01.rtf")



## Deskriptive Statistik Politikbereiche
# Auswahl der Variablen
var_sel <- c("agric_rel_prc_wiki", "econo_rel_prc_wiki", "educ_rel_prc_wiki",
             "cult_rel_prc_wiki", "enven_rel_prc_wiki", "europ_rel_prc_wiki",
             "fntax_rel_prc_wiki", "gndis_rel_prc_wiki", "iasyl_rel_prc_wiki",
             "intrel_rel_prc_wiki", "milit_rel_prc_wiki", "arbmk_rel_prc_wiki",
             "reord_rel_prc_wiki",  "phlth_rel_prc_wiki", "medkom_rel_prc_wiki",
             "vrkhr_rel_prc_wiki", "natzu_rel_prc_wiki", "swelf_rel_prc_wiki")
# Speichern der Tabelle          
data00 %>% 
  select(., var_sel) %>% 
  stargazer(., type = "html", digits = 1, out = "./GrafikenTabellen/descr_polb_draft01.rtf")



## Deskriptive Statistik Wikipedia
var_sel <- c("wrd_no_wiki", "wiki_edt_tot", "wiki_edt_prb_a", "wiki_edt_prb_b",
             "wiki_edt_prb_c", "wiki_pgvw_prd_a", "wiki_pgvw_prd_b", "wiki_pgvw_prd_c",
             "wiki_old_url", "wiki_ezlnk_no", "wiki_wblnk_no")
data00 %>% 
  select(., var_sel) %>% 
  stargazer(., type = "html", digits = 1, out = "./GrafikenTabellen/descr_wiki_draft01.rtf")




## Deskriptive Statistik Plarlamentarier
var_sel <- c("age2019", "rat", "party_short")
             
data00 %>% 
  select(., var_sel) %>% 
  stargazer(., type = "html", digits = 2,
            covariate.labels=c("Alter [yr.]"),
            title="Descriptive statistics",
            out = "./GrafikenTabellen/descr_parl_draft01.rtf")




smry_rat <- summary(data00$rat)
smry_status <- summary(data00$status)
smry_gender <- summary(data00$gender)
smry_party <- summary(data00$party_short)
smry_region <- summary(data00$region)
smry_district <- summary(as.factor(as.character(data00$district)))

smry_parl <- append(smry_rat, smry_status) %>% 
             append(., smry_gender) %>% 
             append(., smry_party) %>% 
             append(., smry_region) %>% 
             append(., smry_district) %>% 
             data.frame(.) %>% 
             `colnames<-`("Anzahl[--]") %>% 
             kable(., "latex") %>%
             kable_styling(latex_options = "striped") %>%
             save_kable("./GrafikenTabellen/test.rtf")


```




